- .github/workflows/lint.yml
- CODEOWNERS
- Added lint check pre-main job
- Copied from [nats-manager](https://github.com/kyma-project/nats-manager/blob/main/.github/workflows/lint.yml)
- https://github.com/kyma-project/eventing-manager/issues/4
> Added lint check pre-main job and updated codeowners

- internal/controller/eventing/controller.go
- test/utils/integration/integration.go
> Fixed flaky unit tests

- api/v1alpha1/zz_generated.deepcopy.go
- internal/controller/eventing/controller.go
- internal/controller/eventing/integrationtests/controller/integration_test.go
- internal/controller/eventing/unit_test.go
- pkg/eventing/deployment.go
- pkg/eventing/manager.go
- pkg/eventing/manager_test.go
- pkg/eventing/utils.go
- pkg/eventing/utils_test.go
- test/utils/integration/integration.go
> Renamed EPP to Publisher

- .reuse/dep5
- change contact information in reuse metadata
> change reuse contact information

- api/v1alpha1/zz_generated.deepcopy.go
- config/samples/operator_v1alpha1_eventing.yaml
- config/samples/operator_v1alpha1_eventing_eventmesh.yaml
- go.mod
- internal/controller/eventing/controller.go
- internal/controller/eventing/eventmesh.go
- internal/controller/eventing/eventmesh_test.go
- internal/controller/eventing/integrationtests/controller/integration_test.go
- internal/controller/eventing/service_instance_secret.go
- pkg/eventing/deployment.go
- pkg/eventing/deployment_test.go
- pkg/eventing/utils.go
- pkg/k8s/client.go
- pkg/k8s/client_test.go
- pkg/k8s/mocks/client.go
- test/utils/integration/integration.go
- test/utils/options.go
Create EPP deployment for EventMesh mode
- Implementation
- Tests
#40
> Event mesh mode

- Makefile
- config/crd/external/applications.applicationconnector.crd.yaml
- config/crd/external/subscriptions.eventing.kyma-project.io.crd.yaml
- config/crd/kustomization.yaml
- config/crd/patches/webhook_in_subscriptions.yaml
- config/default/kustomization.yaml
- config/default/manager_auth_proxy_patch.yaml
- config/default/manager_config_patch.yaml
- config/manager/configmap.yaml
- config/manager/kustomization.yaml
- config/manager/manager.yaml
- config/prometheus/monitor.yaml
- config/rbac/kustomization.yaml
- config/rbac/role.yaml
- config/rbac/webhook_role.yaml
- config/rbac/webhook_role_binding.yaml
- config/rbac/webhook_service_account.yaml
- config/webhook/cronjob.yaml
- config/webhook/job.yaml
- config/webhook/kustomization.yaml
- config/webhook/service.yaml
- config/webhook/webhook_configs.yaml
- internal/controller/eventing/controller.go
- Added webhook cert job and cronjob.
- Added mutating and validating webhook configuration objects.
- Refactored kustomize configs
- https://github.com/kyma-project/eventing-manager/issues/51
> Added webhook cert job and refactored kustomize configs

- e2e/sink/.vscode/launch.json
> Create E2E Tests Workflow (#85)

- hack/e2e/sink/internal/handler/handler.go
Add root / endpoint to store event
> Add root endpoint to store events

- go.mod
- internal/controller/eventing/controller.go
Watch ClusterRole and ClusterRoleBinding resources
> Watch Cluster-Scoped Resources

- api/v1alpha1/zz_generated.deepcopy.go
- pkg/eventing/manager.go
- pkg/eventing/manager_test.go
- pkg/k8s/client.go
- pkg/k8s/client_test.go
- pkg/k8s/mocks/client.go
- test/utils.go
- Support updating publisher deployment created by eventing-controller
- https://github.com/kyma-project/eventing-manager/issues/71
> Support updating publisher deployment created by eventing-controller

- .gitignore
- .version
- Makefile
- hack/ci/Makefile
- module-config-template.yaml
- scripts/release.sh
- sec-scanners-config.yaml
Add tasks in Makefile to build eventing module in the build pipeline
[#81](https://github.com/kyma-project/eventing-manager/issues/81)
> Add tasks for module build in Makefile

- .github/workflows/create-release.yml
- scripts/check_image.sh
- scripts/check_release_tag.sh
- scripts/create_changelog.sh
- scripts/create_draft_release.sh
- scripts/publish_release.sh
- scripts/release.sh
- scripts/verify_status.sh
> Create Release Pipeline

- test/utils/integration/integration.go
the package `"github.com/kyma-project/eventing-manager/api/v1alpha1"` is importet twice. Let's remove one import.
> remove double import

- sec-scanners-config.yaml
Add the latest version security scanners config
> Add the latest version security scanners config

- cmd/main.go
- go.mod
- go.sum
- hack/e2e/common/testenvironment/test_environment.go
- internal/controller/subscription/eventmesh/test/utils.go
- internal/controller/subscription/eventmesh/testwebhookauth/utils.go
- internal/controller/subscription/eventmesh/testwithory/utils.go
- internal/controller/subscription/jetstream/test_utils_test.go
- pkg/eventing/manager_test.go
- pkg/k8s/client.go
- pkg/object/equality_test.go
- test/utils/integration/integration.go
This PR bumps all dependencies and replaces deprecated or deleted functions.
(for an easy review just watch commit by commit and read commit description)
> Bump dependencies

- Dockerfile
> Bump the golang image in the Dockerfile

- config/manager/manager.yaml
> Increase memory limits

- sec-scanners-config.yaml
> Update sec-scanners-config to latest build.

- test/utils/integration/integration.go
> Increase timeout to 90 seconds in integration test.

- sec-scanners-config.yaml
> Update to latest image for release 0.1.0

- .github/workflows/sink.yml
- .github/workflows/validate.yml
Actions on main could no longer be executed ([Example](https://github.com/kyma-project/eventing-manager/actions/runs/6629334544/workflow)) because github actions does not allow defining a `paths` and a `paths-ignore` filter for the same event. Instead, the `!` needs to be used, to exclude paths.
This is documented [here](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-and-excluding-paths) 
- Remove `paths-ignore`
> Cleanup including and excluding paths in github action

- config/manager/kustomization.yaml
- config/manager/manager.yaml
- sec-scanners-config.yaml
- Bump EPP image to latest from main
> Bump EPP image to latest from main

- .version
- sec-scanners-config.yaml
Bump image
- Update version for release 0.1.1
- Bump image
> Update version and image for eventing-manager release 0.1.1

- .github/workflows/lint-markdown-links-pr.yml
- .mlc.config.json
- Add github action for links checker for markdown files
- https://github.com/kyma-project/eventing-manager/issues/206
> Add github action for links checker for markdown files

- sec-scanners-config.yaml
- Added webhook cert image to security scanner config
> Added webhook cert image to security scanner config

- README.md
Add the domain config to the readme.
- https://github.com/kyma-project/eventing-manager/issues/137
> Add the domain config to the readme

- .version
- config/manager/manager.yaml
- sec-scanners-config.yaml
- Bump images and version for Release 1.0.0
> Bump images and version for Release 1.0.0

- config/manager/kustomization.yaml
- sec-scanners-config.yaml
> Add rc-tag to security scanners

- .github/workflows/test.yml
- Makefile
- README.md
- docs/user/troubleshooting/evnt-01-eventing-troubleshooting.md
- Updated readme
- Updated makefile targets to same as in nats-manager
- https://github.com/kyma-project/eventing-manager/issues/128
> Updated readme and makefile

- internal/controller/eventing/integrationtests/controller/integration_test.go
Let's run the integration tests for the CR consecutive.
> Remove parallel test run

- sec-scanners-config.yaml
Image comes from this commit: https://github.com/kyma-project/eventing-manager/commit/04ced8b394a2673ffb7f725e2f989eaac5dea8bd
> Update the sec-scanner-config.yaml to the latest build.

- docs/user/troubleshooting/_sidebar.md
- docs/user/tutorials/_sidebar.md
> Fix navigation files

- .version
- sec-scanners-config.yaml
Update image
- Update version file to 1.0.1
- Update image tag
> Prepare release 1.0.1

- docs/user/resources/_sidebar.md
- Add the `_sidebar.md` file to the `resources` folder in the `user` directory to ensure the correct rendering of all user documents at `kyma-project.io`.
> Add the navigation file to the resources folder

- pkg/eventing/manager.go
- pkg/object/apirule.go
- pkg/object/apirule_test.go
- pkg/object/equality.go
- pkg/object/equality_test.go
- pkg/object/object.go
Increase object pkg test coverage.
- #240
> Increase object pkg test coverage

- .gitignore
- Makefile
Add make target to clean the go test cache.
> Add make target to clean the go test cache

- .version
- sec-scanners-config.yaml
> Bump version for rel 0.0.0

- sec-scanners-config.yaml
- this is a test for the release flow.
> bump the eventing-manager version.

- sec-scanners-config.yaml
> Bump em image

- cmd/main.go
> retrigger build job.

- sec-scanners-config.yaml
> bump again

- scripts/verify-status.sh
> Refactor verify script

- .github/workflows/create-release.yml
- Swap two steps: `Checkout code` and `Verify that the current branch has a name that starts with 'release-'`
> Checkout code

- .github/workflows/create-release.yml
- Release input variable for tag checking
> Release input variable for tag checking

- .github/workflows/create-release.yml
> fix reference to release name

- .github/workflows/create-release.yml
- add missing env vars for MODULE_REGISTRY and IMG
> add missing env vars for IMG and MODULE_REGISTERY

- .github/workflows/create-release.yml
- scripts/render_and_upload_manifests.sh
- replace the BOT_GITHUB_TOKEN with the GITHUB_TOKEN
> fix wrong token

- .github/workflows/create-release.yml
- name: Create and upload eventing-manager.yaml and eCahnge github.event.input.name to
- change spelling from `github.input` to `github.inputs`
> fix spelling of env var name

- .github/workflows/create-release.yml
- scripts/render_and_upload_manifests.sh
Get the fixes to the release pipeline on the branch `release-1.0` back to `main`. 
> Cherry pick fixes to release channel

- api/operator/v1alpha1/zz_generated.deepcopy.go
- internal/controller/operator/eventing/controller.go
- internal/controller/operator/eventing/controller_test.go
- internal/controller/operator/eventing/eventmesh_test.go
- Cleanup EPP resource when switching backends
- https://github.com/kyma-project/eventing-manager/issues/345
> Cleanup EPP resource when switching backends

- sec-scanners-config.yaml
- update the image use in sec-scanner-config 
The used image is latest build at [europe-docker.pkg.dev/kyma-project/prod/eventing-manager](https://console.cloud.google.com/artifacts/docker/kyma-project/europe/prod/eventing-manager)
> bump the image used in sec-scanners-config

- testing/eventmeshmock.go
If err occurs the application is stopping immediately with panic. To prevent this, let's retry the call instead of panicking immediately. The code retries 3 times before it panics.
> Retry instead of panicking immediately

- testing/eventmeshmock.go
> Remove panic from test

- .github/workflows/e2e-k8s.yml
- Fix backend switching initial trigger setup.
- To fix the error: `The workflow is not valid. .github/workflows/e2e-k8s.yml (Line: 19, Col: 3): The workflow must contain at least one job with no dependencies.`
> Fix backend switching initial trigger setup

- docs/user/tutorials/evnt-02-subs-with-multiple-filters.md
- docs/user/tutorials/evnt-03-type-cleanup.md
- docs/user/tutorials/evnt-04-change-max-in-flight-in-sub.md
- docs/user/tutorials/evnt-05-send-legacy-events.md
- Added bold to tabs titles so that they render correctly
> Update tabs config

- config/manager/kustomization.yaml
- sec-scanners-config.yaml
The EM image needs to be bumped to release version 1.1.0
- Bump EM image in `sec-scanners-config.yaml`
- Bump EM image in kustomization
> Bump eventing-manager image version for 1.1.0 release

- .github/workflows/e2e-backend-switching-reuseable.yml
- .github/workflows/e2e.yml
- scripts/gardener/aws/deprovision.sh
- scripts/gardener/aws/provision.sh
- Fixed `wait-build-job` for main branch.
- Updated comments.
https://github.com/kyma-project/eventing-manager/issues/131
> Fixed wait-build-job for main branch

- .github/workflows/create-release.yml
- fix a missing `)` in the `Create release` workflow
> fix broken release workflow

- .github/workflows/create-release.yml
- set the env var PULL_BASE_REF the correct way
> fix the setting of env var PULL_BASE_REF in `Create release`

- .github/workflows/pull-target-e2e.yml
> Fix `is-pr-approved` job

- .github/workflows/pull-target-e2e.yml
- Updated comment in pull-target-e2e workflow.
> Updated comment in pull-target-e2e workflow

- config/samples/default.yaml
- config/samples/default_nats.yaml
- cherry-pick of #419 
https://github.com/kyma-project/eventing-manager/issues/430
> Make default CR have empty backend (#419)

- docs/user/tutorials/evnt-02-subs-with-multiple-filters.md
- docs/user/tutorials/evnt-03-type-cleanup.md
- docs/user/tutorials/evnt-04-change-max-in-flight-in-sub.md
- docs/user/tutorials/evnt-05-send-legacy-events.md
- Updated a link to a section detected by the custom link check
> Fix broken links

- docs/user/README.md
> Update a link

- .github/workflows/e2e-backend-switching-reuseable.yml
- Update Eventing CR used in backend-switching job, because the default.yaml has an empty backend now.
> Update Eventing CR used in backend-switching job

- docs/user/README.md
- docs/user/evnt-architecture.md
- docs/user/evnt-event-names.md
- docs/user/resources/evnt-cr-subscription.md
- docs/user/troubleshooting/README.md
- docs/user/troubleshooting/evnt-04-free-jetstream-storage.md
- docs/user/tutorials/evnt-02-subs-with-multiple-filters.md
- docs/user/tutorials/evnt-03-type-cleanup.md
- docs/user/tutorials/evnt-04-change-max-in-flight-in-sub.md
- docs/user/tutorials/evnt-05-send-legacy-events.md
- fix name of the EPP
- headline in title case
- minor language editing
> docs: Fix spelling, incl EventING Publisher Proxy

- docs/user/evnt-event-names.md
- docs/user/resources/evnt-cr-subscription.md
> Fix md links

- sec-scanners-config.yaml
- Changed image tag to main in sec-scanners-config, so we do not have to bump the tag everytime.
> Changed image tag to main in sec-scanners-config

- sec-scanners-config.yaml
In order for the security scans to be executed correctly, the rc-tag needs to point to the latest release, when releasing to a channel.
> Bump rc-tag on main to 1.1.0

- README.md
- docs/user/resources/evnt-cr-subscription.md
- docs/user/troubleshooting/evnt-04-free-jetstream-storage.md
- docs/user/tutorials/evnt-02-subs-with-multiple-filters.md
- docs/user/tutorials/evnt-03-type-cleanup.md
- docs/user/tutorials/evnt-04-change-max-in-flight-in-sub.md
- docs/user/tutorials/evnt-05-send-legacy-events.md
- We're now using the docsify plugin so that the notes, tips, and cautions are prettier
https://github.com/kyma-project/kyma/issues/18552
> docs: Apply the flexible alerts plugin to Eventing docs

- .github/workflows/e2e-backend-switching-reuseable.yml
- .github/workflows/e2e-upgrade-test-reusable.yaml
- .github/workflows/e2e.yml
- Dockerfile
- Makefile
- go.mod
- go.sum
- Bump to Go version `1.22.0` in multiple files.
> Chore: bump Golang version to 1.22.0

- hack/e2e/common/retry.go
[Staticcheck](https://staticcheck.dev/) does not like the `Retry` and `RetryGet` functions we use in the `e2e` tests, so let's improve them:
- Simplify the `Retry` functions.
**Tests**
Issues with changes would be caught via the `e2e` tests.
**Related**
https://github.com/kyma-project/nats-manager/pull/335
> Simplify retry function

- README.md
- docs/contributor/installation.md
- docs/user/tutorials/evnt-01-prerequisites.md
- we had inconsistent prepositions, this should fix it.
- ...
- ...
> docs: Switch preposition, its IN a cluster not ON a cluster

- docs/user/resources/evnt-cr-subscription.md
- removed v1alpha1 subscription specifications from doc: https://kyma-project.io/#/eventing-manager/user/resources/evnt-cr-subscription?id=subscriptioneventingkyma-projectiov1alpha1
- https://github.com/kyma-project/eventing-manager/issues/442
> chore: removed v1alpha1 subscription specifications from doc

- docs/user/troubleshooting/README.md
- Fixed the link to the community Kyma Slack channel
> docs: Fix link to Kyma Slack channel

- .github/workflows/lint-conventional-prs.yml
> fix: check title gh-action

- api/operator/v1alpha1/zz_generated.deepcopy.go
- internal/controller/operator/eventing/status.go
- internal/controller/operator/eventing/status_test.go
- updated conditions to check for readiness of deployment
- https://github.com/kyma-project/eventing-manager/issues/225
> fix: updated conditions to check for readiness of deployment

- docs/user/troubleshooting/evnt-05-fix-pending-messages.md
- Add additional trouble shooting steps
> docs: improve the troubleshooting guide for Eventing

- hack/ci/Makefile
- scripts/gardener/aws/provision.sh
- Deprecate `kyma provision gardener`
- https://github.com/kyma-project/kyma/issues/18674
> chore: deprecate kyma provision gardener

- scripts/gardener/aws/provision.sh
- Fix typo in Gardener provisioning
- #572
> fix: fix typo in Gardener provisioning

- config/ui-extensions/eventing/general
- Unify CR description in Kyma dashboard and update the docu link
[#18321](https://github.com/kyma-project/kyma/issues/18321)
> fix: unify CR description in Kyma dashboard

- .github/workflows/k8s-compatibility-test.yml
- fixed k8s compatibility check job to use provided k8s version
> fix: fixed k8s compatibility check job to use provided k8s version

- docs/user/01-manager.md
> docs: change enable and disable to add and delete in the eventing repo

- .github/workflows/k8s-compatibility-test.yml
- hack/ci/Makefile
- scripts/gardener/aws/provision.sh
> chore: fix k8s compatibility test

- Dockerfile
- go.mod
bump image in:
- go.mod
- Dockerfile
> chore: bump go version to 1.22.6

- CONTRIBUTING.md
- Updated CONTRIBUTING.md
https://github.com/kyma-project/community/issues/926
> docs: update the contributing file

- config/manager/manager.yaml
- Update epp version to 1.1.0 in eventing-manager config
> chore: update epp version to 1.1.0 in eventing-manager config

- .github/workflows/pull-build-image.yaml
- .github/workflows/push-build-image.yaml
- .github/workflows/tag-build-image.yaml
- Dockerfile
- added github action based build jobs
- changed Dockerfile working directory because of error:
```
2024-09-16T08:07:03.1145549Z ValueError: Dockerfile cannot use /workspace as the working directory. Please switch to another one (e.g., /<module>-workspace). See: https://github.com/GoogleContainerTools/kaniko/issues/3176 and https://github.com/GoogleContainerTools/kaniko/issues/2192
```
> chore: added github action based build jobs

- Dockerfile
- go.mod
- bump golang version from 1.23.0 to 1.23.1
> chore: bump golang version to 1.23.1

- docs/contributor/testing.md
- remove prow reference
- https://github.com/kyma-project/eventing-manager/issues/636
> fix: remove prow reference

- api/operator/v1alpha1/zz_generated.deepcopy.go
- go.mod
- go.sum
- internal/controller/operator/eventing/mocks/typed_controller.go
- pkg/backend/jetstream/mocks/JetStreamContext.go
- pkg/backend/jetstream/stubs_test.go
- testing/test_helpers.go
- bump nats from 1.36.0 to 1.37.0
- fix breaking changes
> chore: bump nats to 1.37.0

- config/manager/manager.yaml
> chore: bump EPP version to 1.1.1

- config/manager/kustomization.yaml
Revert kustomization.yaml to the previous version.
> Revert kustomization.yaml

- README.md
The file Makefile Helpers has been removed from kubebuilder documentation with this [PR](https://github.com/kubernetes-sigs/kubebuilder/pull/4184).
> docs: remove a broken link

- docs/user/tutorials/evnt-02-subs-with-multiple-filters.md
- docs/user/tutorials/evnt-03-type-cleanup.md
- docs/user/tutorials/evnt-04-change-max-in-flight-in-sub.md
- docs/user/tutorials/evnt-05-send-legacy-events.md
- Update broken links to Istio documentation
https://github.com/kyma-project/istio/pull/999
> docs: update broken links

- .github/workflows/e2e.yml
- .github/workflows/lint-go.yml
- .github/workflows/pull-e2e-upgrade-test.yaml
- .github/workflows/pull-target-e2e.yml
- .golangci.yaml
- the value of `linters-settings.wrapcheck.ignorePackageGlobs` was changed from `null` to an empty array (`[]`).
- the `skip-files` section is misplaced and was moved into the `issues` section.
- fix the trigger for some GH workflows: for `on.pull_request` the property `apth-ignores` is not allowed, so it was replaced with `paths` and the appropriate files that should trigger the workflow.
> fix: linter config

- .github/workflows/k8s-compatibility-test.yml
- hack/e2e/scripts/expose_epp_and_sink.sh
- fixed k8s compatibility test job
> fix: fixed k8s compatibility test job

- hack/e2e/common/testenvironment/test_environment.go
- increased retry attempts in e2e tests
> fix: increased retry attempts in e2e tests

- hack/ci/Makefile
- hack/e2e/scripts/expose_epp_and_sink.sh
- fixed waiting for eventing in k8s compatibility job
> fix: fixed waiting for eventing in k8s compatibility job

- hack/e2e/common/fixtures/fixtures.go
- enable istio side car injection in test namespace
> enable istio sidecar injection in test-namespace

- .github/workflows/e2e-backend-switching-reuseable.yml
> chore: e2e-backend-switching-reuseable env var E2E_LOG_LEVEL: debug

- .github/workflows/create-release.yml
> chore: update create-release.yml
