kyma-project/eventing-manager

.github/workflows/validatecrd.yml
this adds a simple gh action that tries to apply the eventing-crd to a k3d cluster to see if it is compliant. this is especially useful if you are working on the CRD.
=> add a gh action to validate the crd

pkg/eventing/deployment.go
Set deployment replica to nil so that HPA controls the deployment. Otherwise whenever a deployment is applied it sets the replicate to different than HPA wants.
=> Prevent HPA and Deployment Replica Fight

Makefile, hack/e2e/common/eventing/publisher.go, hack/e2e/common/eventing/sinkclient.go, hack/e2e/common/eventing/utils.go, hack/e2e/common/fixtures/fixtures.go, hack/e2e/common/http/http.go, hack/e2e/common/testenvironment/test_environment.go, hack/e2e/env/env.go, hack/e2e/eventing/cleanup/cleanup_test.go, hack/e2e/eventing/delivery/delivery_test.go, hack/e2e/eventing/eventing_test.go, hack/e2e/eventing/setup/setup_test.go, hack/e2e/scripts/event_delivery_tests.sh
- Added tests for Cloud Events and verification of reception of events by the Sink
- https://github.com/kyma-project/eventing-manager/issues/74
=> Added tests for Cloud Events and verification of reception of events by the Sink

README.md, hack/e2e/.env.template, hack/e2e/README.md
- Added documentation for e2e tests
- https://github.com/kyma-project/eventing-manager/issues/74
=> Added documentation for e2e tests

api/v1alpha1/eventing_types.go, api/v1alpha1/status.go, api/v1alpha1/zz_generated.deepcopy.go, internal/controller/eventing/controller.go, internal/controller/eventing/integrationtests/controller/integration_test.go, internal/controller/eventing/status.go, pkg/k8s/client.go, pkg/k8s/client_test.go, pkg/k8s/mocks/client.go, test/utils/integration/integration.go
* Cluster role and binding were not deleted as k8s garbage collector cannot delete if namespace scoped owns cluster scoped
* Add tests
* Improve conditions
=> Delete Cluster Scoped Resources

hack/e2e/eventing/delivery/delivery_test.go, hack/e2e/eventing/setup/setup_test.go
the unit tests are failing because the e2e-test unintentionally get triggered due to the missing build tags. this pr adds them.
=> Add missing build tags to e2e tests

config/manager/manager.yaml, config/rbac/auth_proxy_role_binding.yaml, config/rbac/auth_proxy_service.yaml, config/rbac/leader_election_role_binding.yaml, config/rbac/role_binding.yaml, config/rbac/service_account.yaml, config/webhook/kustomization.yaml, config/webhook/webhook_configs.yaml
- Fixed webhooks
- Renamed service-account
- https://github.com/kyma-project/eventing-manager/issues/101
=> Fixed webhooks and renamed service-account

.github/workflows/e2e.yml, cmd/main.go, hack/ci/Makefile, hack/ci/check-k8s-resource-is-ready.sh, hack/ci/check-nats-ready.sh, hack/e2e/common/testenvironment/test_environment.go, hack/e2e/setup/setup_test.go
this PR adds a github action to execute the e2e test with nats as a backend. the eventing manager will be deployed without the lifecycle manager.
=> create ghithub action to run the end-to-end tests without lifecycle manager with nats as a backend

pkg/eventing/deployment.go
`FromInt` is deprecated; let's use `FromInt32` instead.
https://github.com/kubernetes/apimachinery/blob/v0.28.2/pkg/util/intstr/intstr.go#L58
=> replace intstr.FromInt with instr.FromInt32

.github/workflows/e2e.yml, .github/workflows/lint.yml, .github/workflows/sink.yml, .github/workflows/test.yml, .github/workflows/validate.yml
This PR tweaks the way github action workflows get triggered:
- changes to `docs/` and to `.md` files will not trigger any workflow
- only changes to `api/` and `config/crd` will trigger the CRD validation
=> streamline how github action workflows get triggered

pkg/backend/jetstream/jetstream.go, pkg/backend/metrics/collector.go
- add additional label 'consumer_name' onto metrics
=> add additional label consumer name on dispatching metrics

internal/controller/eventing/nats.go, internal/controller/eventing/nats_test.go
Fix nats stream replicas update
* Set subscription manager to nil if spec is changed to create subscription manager with new values
#211
=> Fix nats stream replica update

Dockerfile, config/default/kustomization.yaml, config/ui-extensions/eventing/kustomization.yaml, config/ui-extensions/subscriptions/subscriptions.yaml, internal/controller/operator.kyma-project.io/eventing/controller.go, internal/controller/operator.kyma-project.io/eventing/eventmesh.go, internal/controller/operator.kyma-project.io/eventing/eventmesh_test.go, internal/label/label.go, pkg/eventing/deployment.go, pkg/eventing/deployment_test.go, pkg/eventing/manager.go, pkg/eventing/utils.go, pkg/eventing/utils_test.go, pkg/object/equality_test.go
Use common labels.
- https://github.com/kyma-project/eventing-manager/issues/259
=> Use common labels

cmd/main.go, internal/controller/cache/cache.go, internal/controller/cache/cache_test.go, internal/controller/client/client.go, internal/controller/client/client_test.go, internal/label/label.go, internal/label/label_test.go
Cache runtime objects only created by the EventingManager.
- https://github.com/kyma-project/eventing-manager/issues/258.
=> Cache runtime objects only created by the EventingManager

scripts/verify-status.sh
-We were facing the following issue during Prow job verification:
```bash
curl: (23) Failed writing body
{ "state": "pending",
Jobs failed or pending - Check Prow status
Error: Process completed with exit code 1.
```
- Then we realized the status API was called immediately after the starting, therefore the state will be Faliled or Pending every time.
- Added some extra output and parse the results with `jq`
=> Improve Prow job verification script

config/samples/empty_backend.yaml, config/ui-extensions/eventing/details, config/ui-extensions/eventing/form, config/ui-extensions/eventing/kustomization.yaml
=> Update UI with improved notifications

.github/workflows/create-release.yml, scripts/check_tag_info.sh
- Use name variable at tag check
- Remove white space at rc-tag
=> Release input variable for tag checking

.github/workflows/create-release.yml, scripts/verify-status.sh
- `INITIAL_WAIT_TIME` parameter to wait before check the api
=> Initial Wait Time

.github/workflows/e2e.yml, .github/workflows/lint.yml, .github/workflows/sink.yml, .github/workflows/test.yml, .github/workflows/validate.yml
- run the github action workflow also against release branches.
=> Run github action workflows on release-branches.

.github/workflows/create-release.yml, scripts/render_and_upload_manifests.sh
The prow job `release-eventing-manager-module-build` [was removed](https://github.com/kyma-project/test-infra/pull/9517/files). It used to run the `scripts/release.sh` script, so let's run it now from the `create-release.yml` 
- clean up
- deactivate the upload of the `module-template.yml` (since it is no longer needed) 
- render and upload all release-related manifests directly from the github-action-workflow `Create release`.
=> Fix release of manifests

.github/workflows/create-release.yml, scripts/render_and_upload_manifests.sh
* clean up create-release.yml
Clean up the create-release.yml by removing a number of unused and outcommented lines.
* rename release.sh to render_and_upload_manifests.sh
Rename the scripts/release.sh to render_and_upload_manifests.sh to point clearly out, what the script is about.
* call manifest release from create-release.yml
Call the render_and_upload_manifests.sh because it no longer created by a prow job.
* deactivate module-template upload
Deactivate the upload of the module-template. All functionality for the module-template will be removed eventually, in a follow up PR.
* fix reference of env var
- Cherry-pick the changes done to `create release` to the `release-1.0` branch.
=> Cheery-pick: fix release of manifests (#340)

.github/workflows/create-release.yml, scripts/render_and_upload_manifests.sh
We really only need to render the manifests so lets remove module-build.
in the release action, we do not need make build module, so let's remove it.
- remove `make build-module`
=> remove call of make module-build

internal/controller/operator/eventing/eventmesh.go, internal/controller/operator/eventing/eventmesh_test.go
Improve EventMesh tests
- Don't use require.ErrorAs as it only compares types. Instead error should be compared properly.
- Change business logic to make it mockable
[#334](https://github.com/kyma-project/eventing-manager/issues/334)
=> Improve EventMesh Tests for Better error comparison

.github/workflows/e2e.yml, hack/ci/Makefile, testing/eventmeshmock.go
Install NATS module without lifecycle manager
=> Fix e2e job NATS Install step

internal/controller/cache/cache.go, internal/controller/cache/cache_test.go, internal/label/label.go, internal/label/label_test.go
Use the `app.kubernetes.io/created-by` label to cache runtime objects.
⚠️ Caution ⚠️
This PR should be merged only after the label `app.kubernetes.io/created-by=eventing-manager` is released to PROD.
=> Use created-by label to cache runtime objects

.github/workflows/create-release.yml, scripts/check_sec-scanners-config.sh, scripts/render_and_upload_manifests.sh
Creating a release will no longer require manual input of a version number; the version number will get generated automatically.
- use [script](script](https://raw.githubusercontent.com/kyma-project/eventing-tools/main/hack/scripts/get-version-from-branch.sh)) to generate release version
- renamed script `check_tag_info.sh` to `scripts/check_sec-scanners-config.sh` for [consistent naming](https://github.com/kyma-project/nats-manager/blob/main/.github/scripts/check_sec-scanners-config.sh) between repos.
For the lack of a better method, this was conceptually tested [here](https://github.com/friedrichwilken/test-gha/actions/runs/7531147017/job/20499066155) based on [this workflow](https://github.com/friedrichwilken/test-gha/blob/release-1 …
=> Release without version input

.github/workflows/e2e-backend-switching-reuseable.yml, .github/workflows/e2e.yml, hack/ci/Makefile, scripts/extract_image_from_build_logs.sh, scripts/gardener/aws/deprovision.sh, scripts/gardener/aws/provision.sh, scripts/ias/create-ias-app.sh, scripts/ias/delete-ias-app.sh, scripts/utils/log.sh, scripts/utils/utils.sh
- Added backend switching job re-useable workflow template for EventMesh on push event.
- Called the re-useable workflow template in `e2e.yml` workflow for only push event..
- Updated the `wait-until-build-succeeds` to output the `image-name`, so other jobs can use the image.
- Added `push` event in e2e workflow, so all the jobs in this workflow will also run on main/release branches.
=> Add backend switching job for EventMesh on Push event

.github/workflows/e2e-backend-switching-reuseable.yml, hack/e2e/scripts/event_delivery_tests.sh, hack/e2e/scripts/expose_epp_and_sink.sh, scripts/cleanup_modules.sh
- Updated backend switching job to use API Rules instead of port-forward
- Added a step to cleanup cluster before deleting gardener cluster, otherwise the deletion stucks.
- Test run: [link](https://github.com/kyma-project/eventing-manager/actions/runs/7553998523/job/20566057872?pr=392)
=> Updated backend switching job to use API Rules instead of port-forward

config/manager/manager.yaml, sec-scanners-config.yaml
With the new release of the [eventing-publisher-proxy:1.0.1](https://github.com/kyma-project/eventing-publisher-proxy/releases/tag/1.0.1) the image in the eventing-manager needs to be updated to this version.
- Update EPP image to 1.0.1
[eventing-publisher-proxy/#45](https://github.com/kyma-project/eventing-publisher-proxy/issues/45)
=> Update eventing-publisher-proxy to image 1.0.1

.github/workflows/e2e.yml
Remove lifecycle manager names from jobs as by default KLM is not used anymore for the tests
https://github.com/kyma-project/nats-manager/issues/228
=> Remove lifecycle manager names from jobs

README.md, scripts/cleanup_modules.sh, scripts/render_and_upload_manifests.sh
The name of the `manager.yaml` needs to use `-` instead of `_`
=> Correct `manager.yaml` name

.github/workflows/create-release.yml, README.md, scripts/cleanup_modules.sh, scripts/render_and_upload_manifests.sh
Cherry-pick fixes to the `create release` workflow on the `release-1.1` branch to the `main branch`:
- #413 
- #415
- #416
- #417
=> Cherry pick changes to release workflow

.github/workflows/e2e-backend-switching-reuseable.yml, .github/workflows/pull-target-e2e.yml, scripts/gardener/aws/get_random_region.sh, scripts/gardener/aws/provision.sh, scripts/is_pr_approved.sh, scripts/utils/utils.sh
- Assigns random region for Gardener cluster in backend switching job.
=> Get random region for Gardener cluster in backend switching job and check for is-PR-approved

docs/user/tutorials/evnt-02-subs-with-multiple-filters.md, docs/user/tutorials/evnt-03-type-cleanup.md, docs/user/tutorials/evnt-04-change-max-in-flight-in-sub.md, docs/user/tutorials/evnt-05-send-legacy-events.md
- Added missing steps for verifying the event delivery in all four tutorials. The link to the Get Started doesn't work as the document no longer exists. 
=> Add missing steps

.gitignore, Makefile, module-config-template.yaml, scripts/render_and_upload_manifests.sh
Remove module-template from the eventing-manager repo because it is not relevant for OS usage.
- https://github.com/kyma-project/eventing-manager/issues/277
=> Remove module-template

.github/workflows/push-e2e-upgrade-test.yaml
Build job for main push was incorrectly specified. Correct it with post-eventing-manager-build.
Main merge build job was incorrect `push-eventing-manager-build`
=> Correct post-eventing-manager-build name

internal/controller/operator/eventing/controller.go, internal/controller/operator/eventing/integrationtests/natsconnection/integration_test.go, test/utils/integration/integration.go
Change Eventing CR status to WARN if cannot connect to NATS, because this is something the Eventing user can fix. As part of this PR, I removed unused function calls from the connection mock.
- https://github.com/kyma-project/eventing-manager/issues/267
=> Change Eventing CR status to WARN if cannot connect to NATS

.github/workflows/e2e-upgrade-test-reusable.yaml, .github/workflows/pull-e2e-upgrade-test.yaml, .github/workflows/push-e2e-upgrade-test.yaml
Use checkout GH action branch setting
* Set branch with checkout GH action
* Don't set branch for post upgrade checkout
* Use commit sha to checkout latest new version
post upgrade job failed
=> Use checkout GH action branch setting

.github/workflows/e2e-upgrade-test-reusable.yaml
Embed the script logic into the GH action workflow as the script is not found in the latest release
**Reason:**
When latest release is checked out the shell script was missing
=> Don't use shell script file in GHA workflow

docs/user/02-configuration.md
Fix eventing state doc formatting
#328
=> doc: Fix Eventing State doc formatting

hack/ci/Makefile
- bump k3d-version used in tests**
- update version used on gardener**
=> chore: bump k8s version used in tests

.github/workflows/lint-go.yml, internal/controller/operator/eventing/controller.go, internal/controller/operator/eventing/controller_test.go, internal/controller/operator/eventing/eventmesh.go, internal/controller/operator/eventing/eventmesh_test.go, internal/controller/operator/eventing/integrationtests/controller/integration_test.go
- A malformatted EventMesh Secret no longer causes the error status but the warning status.
- Changes the linter to the common linter.
https://github.com/kyma-project/eventing-manager/issues/490
=> fix: Malformatted EventMesh Secret causes warning status

docs/user/troubleshooting/evnt-01-eventing-troubleshooting.md
- Fix the link to Kyma Slack channels (in [`evnt-01-eventing-troubleshooting.md`](https://github.com/kyma-project/eventing-manager/blob/main/docs/user/troubleshooting/evnt-01-eventing-troubleshooting.md))
=> Fix the link to Kyma Slack channels

hack/e2e/common/eventing/testsubscriptioninfo.go, hack/e2e/common/eventing/utils.go, hack/e2e/common/fixtures/fixtures.go, hack/e2e/common/k8s.go, hack/e2e/common/testenvironment/test_environment.go, hack/e2e/eventing/delivery/delivery_test.go
Remove subscription v1alpha1 tests.
- #442
=> chore: remove subscription v1alpha1 tests

.github/workflows/create-release.yml, hack/ci/await-pr-merge.sh
- added job to bump the rc-tag in the sec-scanners-config on main branch in `Create release` workflow.
- https://github.com/kyma-project/eventing-manager/issues/489
=> feature: added job to bump the rc-tag in the sec-scanners-config on main branch when creating release

api/operator/v1alpha1/status.go
…date
- added comments to explain that LastTransistionTime will not update.
- As per the definition of [meta.SetStatusCondition](https://github.com/kubernetes/apimachinery/blob/d82afe1e363acae0e8c0953b1bc230d65fdb50e2/pkg/api/meta/conditions.go#L31), the LastTransitionTime will only be updated when `Status` is changed.
- https://github.com/kyma-project/eventing-manager/issues/542
=> chore: added comments to explain that LastTransistionTime will not update

.github/workflows/create-release.yml, .github/workflows/lint-go.yml, .github/workflows/sink.yml, .golangci.yaml, Makefile, api/operator/v1alpha1/status_test.go, internal/controller/errors/skip.go, internal/controller/eventing/subscription/jetstream/test_utils_test.go, internal/controller/operator/eventing/eventmesh_test.go, internal/controller/operator/eventing/integrationtests/controller/integration_test.go, internal/controller/operator/eventing/nats_test.go, pkg/backend/cleaner/eventmesh.go, pkg/backend/jetstream/config_internal_unit_test.go, pkg/backend/jetstream/jetstream_integration_test.go, pkg/utils/utils_unit_test.go, pkg/watcher/watcher.go, test/utils/integration/integration.go, testing/eventmeshmock.go
- update golangci to 1.57
- use go-version from go.mod
=> chore: update golangci to 1.57

.github/workflows/e2e-backend-switching-reuseable.yml, hack/ci/Makefile
- Change NATS CR wait for Warning status in backend-switching job, because in the latest version of nats-manager the CR will be in Warning state when the k8s is spread across less than 3 availability zones.
=> fix: change NATS CR wait for Warning status

.github/workflows/k8s-compatibility-test.yml, hack/ci/Makefile
- Added github action for K8s version compatibility check.
=> chore: added github action for K8s version compatibility check

hack/ci/Makefile, scripts/gardener/aws/provision.sh
- fixed gardener provisioning make target to use correct env
=> fix: fixed gardener provisioning make target to use correct env

docs/user/02-configuration.md
Currently the link for the default CR which uses `NATS` backend is pointing to the one that has no backend. This PR fixes this.
- fix link to the default cr for the NATS backend
=> fix: link to default CR for NATS in docs

.github/workflows/lint-go.yml, .golangci.yaml, Makefile, hack/e2e/common/fixtures/fixtures.go, internal/controller/eventing/subscription/jetstream/reconciler.go, internal/controller/operator/eventing/integrationtests/validation/integration_test.go, pkg/ems/api/events/client/client.go, pkg/eventing/utils.go, pkg/tracing/tracing.go, pkg/tracing/tracing_test.go, test/utils/utils.go, testing/test_helpers.go
=> fix: bump golint version to fix failing job

api/eventing/v1alpha2/subscription_types.go, api/operator/v1alpha1/eventing_types.go, config/crd/bases/eventing.kyma-project.io_subscriptions.yaml, config/crd/bases/operator.kyma-project.io_eventings.yaml
- Add proper categories for telemetry CRDs according to linked ADR
- ...
- ...
- https://github.com/kyma-project/community/issues/912
=> feat: add proper categories for CRDs

config/manager/manager.yaml
Cherry-pick the following commits from main to release a new EM version `1.2.2`:
- 8f948f0 (HEAD -> main, upstream/main) Bump EPP version to 1.1.1 (#657)
=> chore: bump EPP version to 1.1.1

hack/e2e/scripts/expose_epp_and_sink.sh
- fix the matcher label to allow internal trafic to test sink workload
=> chore: fix the label for AuthPolicy workload matcher
